<a href="https://colab.research.google.com/github/AbdelazizHimmi/Complete-Python-3-Bootcamp/blob/master/Numpy%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
my_list = [1,2,3,6,5,5]
arr = np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 6 5 5]


In [14]:
arr.shape

(6,)

In [18]:
arr.reshape(2,3)

array([[1, 2, 3],
       [6, 5, 5]])

In [37]:
lis = [[1,2,3],[2,3,4],[4,5,6]]
lis = np.array(lis)

In [21]:
np.shape(lis)

(3, 3)

In [24]:
lis2 = np.reshape(lis,(1,9))

In [27]:
lis

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [40]:
np.shape(lis)

(3, 3)

In [38]:
lis[1:,1:]


array([[3, 4],
       [5, 6]])

In [39]:
lis[1:2,1:]

array([[3, 4]])

In [44]:
lis3 = np.arange(0,12,2, dtype=int)
lis3

array([ 0,  2,  4,  6,  8, 10])

In [51]:
lis3 = np.reshape(lis3, (2,3))

In [53]:
lis3

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [56]:
lis3[:1,:1 ]

array([[0]])

In [62]:
lis4 = np.linspace(1,10,num=50,axis=0, retstep=True)
lis4

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
         2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
         4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
         6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
         8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]),
 0.1836734693877551)

In [69]:
lis[3:]=10
lis = np.reshape(lis,9)
lis[3:]=10
lis

array([ 1,  2,  3, 10, 10, 10, 10, 10, 10])

In [76]:
lis[lis < np.max(lis)]

array([1, 2, 3])

In [85]:
liste = np.random.randint(3,15,size=16)
liste = np.reshape(liste,(8,2))

In [90]:
liste = np.random.randn(4,6)
liste
import matplotlib.pyplot as plt
plt.show(liste)

ValueError: ignored

In [86]:
liste[liste<np.median(liste)]

array([3, 6, 8, 8, 5, 6, 7, 6])